//! Program marks for pane rows.
//!
//! A pane's foreground program gets a mark when it is one of these, so an
//! editor, a build or a database client is recognisable at a glance. Unknown
//! programs carry the pane's own mode mark instead, and a user adds their own
//! in `[processes]`.
//!
//! The glyphs are Nerd Font codepoints (the font's own assignments, also used
//! by other tools); this selection is Radar's, kept small on purpose. They are
//! drawn only when a Nerd Font is installed, because a terminal without one
//! shows tofu rather than a mark.

/// Program name (as reported in the foreground command) and its Nerd Font mark.
pub const PROCESS_ICONS: &[(&str, &str)] = &[
    ("nvim", "\u{e6ae}"),
    ("vim", "\u{e62b}"),
    ("vi", "\u{e62b}"),
    ("hx", "\u{f0524}"),
    ("emacs", "\u{e632}"),
    ("nano", "\u{f040}"),
    ("htop", "\u{eba2}"),
    ("btop", "\u{eba2}"),
    ("top", "\u{eba2}"),
    ("btm", "\u{eba2}"),
    ("glances", "\u{eba2}"),
    ("ssh", "\u{f08c0}"),
    ("git", "\u{e702}"),
    ("gitui", "\u{e702}"),
    ("lazygit", "\u{e702}"),
    ("tig", "\u{e702}"),
    ("jj", "\u{e725}"),
    ("lazyjj", "\u{e725}"),
    ("hg", "\u{e727}"),
    ("svn", "\u{e725}"),
    ("docker", "\u{f308}"),
    ("lazydocker", "\u{f308}"),
    ("kubectl", "\u{f10fe}"),
    ("k9s", "\u{f10fe}"),
    ("helm", "\u{f10fe}"),
    ("python", "\u{e73c}"),
    ("python3", "\u{e73c}"),
    ("pip", "\u{e73c}"),
    ("node", "\u{e718}"),
    ("npm", "\u{e71e}"),
    ("yarn", "\u{e718}"),
    ("deno", "\u{eb52}"),
    ("go", "\u{e627}"),
    ("rustc", "\u{e7a8}"),
    ("cargo", "\u{e7a8}"),
    ("java", "\u{e256}"),
    ("ruby", "\u{e23e}"),
    ("php", "\u{e73d}"),
    ("perl", "\u{e769}"),
    ("gcc", "\u{e61e}"),
    ("clang", "\u{e61e}"),
    ("make", "\u{e624}"),
    ("cmake", "\u{e624}"),
    ("gradle", "\u{e7a9}"),
    ("maven", "\u{e7b4}"),
    ("psql", "\u{e76e}"),
    ("mysql", "\u{e704}"),
    ("sqlite", "\u{f1c0}"),
    ("redis", "\u{e76d}"),
    ("mongo", "\u{e7a4}"),
    ("tmux", "\u{ebc8}"),
    ("screen", "\u{ebc8}"),
    ("zsh", "\u{e795}"),
    ("bash", "\u{e795}"),
    ("fish", "\u{e795}"),
    ("nu", "\u{e795}"),
    ("sudo", "\u{f132}"),
    ("curl", "\u{f019}"),
    ("wget", "\u{f019}"),
    ("zip", "\u{f1c6}"),
    ("unzip", "\u{f1c6}"),
    ("rsync", "\u{f021}"),
    ("systemctl", "\u{f085}"),
    ("lf", "\u{f07c}"),
    ("ranger", "\u{f07c}"),
    ("yazi", "\u{eb39}"),
    ("bat", "\u{f0b5f}"),
    ("topgrade", "\u{f06b0}"),
    ("just", "\u{e795}"),
    ("openssl", "\u{f023}"),
];
